In [ ]:
# the code for updating the parameters in question 2
import tensorflow as tf
import keras

x = tf.constant([-0.04, -0.42],shape=[1, 2],dtype=tf.float32) # sets the input [X1, X2]

w1 = tf.constant([[-2.5, -1.5],[0.6, 0.4]]) #setting the weight matrix for first fully connected layer [w1, w2];[w3, w4]
w2 = tf.constant([[-0.1, 2.4, -2.2],[-1.5, -5.2, 3.7]]) #setting the weight matrix for second fc layer [w5, w6, w7];[w8, w9, w10]

t = tf.constant([[0, 1, 0]], dtype=tf.float32) # sets the target matrix [t1, t2, t3]

b1 = tf.constant([-1.6, 0.7]) #sets the bias1.
b2 = tf.constant([0, 0, 1], dtype=tf.float32) #sets the bias2.

def forward(x,w1,w2,b1,b2):
    sum1=tf.matmul(x,w1)+b1
    H = tf.nn.sigmoid(sum1)
    print(H)
    sum2=tf.matmul(H,w2)+b2
    O = tf.nn.softmax(sum2)
    return O

O = forward(x, w1, w2, b1, b2)

print('Forward path output is:', O.numpy())

def backward(x,w1,w2,b1,b2,t):
    with tf.GradientTape() as g:
       g.watch([w1,w2,x,b1,b2])
       O = forward(x, w1, w2, b1, b2)
       Etotal = tf.losses.categorical_crossentropy(t, O)
       print("Total loss = " , Etotal.numpy())
    dEtotal_dw = g.gradient(Etotal, [w1,w2,x,b1,b2]) #calculates the gradients for each part
    dEtotal_dw1, dEtotal_dw2, dEtotal_dx, dEtotal_db1, dEtotal_db2 = dEtotal_dw
    return dEtotal_dw1,dEtotal_dw2,dEtotal_dx,dEtotal_db1,dEtotal_db2

dEtotal_dw1,dEtotal_dw2,dEtotal_dx,dEtotal_db1,dEtotal_db2 = backward(x,w1,w2,b1,b2,t)


w1 = w1 - 0.5*dEtotal_dw1 #the learning rate is set to be 0.5
w2 = w2 - 0.5*dEtotal_dw2

b1 = b1 - 0.5*dEtotal_db1
b2 = b2 - 0.5*dEtotal_db2

print("w1 grad:",dEtotal_dw1)
print('The new w1 is:')
print(w1.numpy())
print("w2 grad:",dEtotal_dw2)
print('The new w2 is:')
print(w2.numpy())
print("b1 grad:",dEtotal_db1)
print('The new b1 is:')
print(b1.numpy())
print("b2 grad:",dEtotal_db2)
print('The new b2 is:')
print(b2.numpy())

tf.Tensor([[0.14779511 0.64382386]], shape=(1, 2), dtype=float32)
Forward path output is: [[0.01729538 0.00231123 0.9803934 ]]
tf.Tensor([[0.14779511 0.64382386]], shape=(1, 2), dtype=float32)
Total loss =  [6.069976]
w1 grad: tf.Tensor(
[[ 0.02293857 -0.0806224 ]
 [ 0.240855   -0.84653515]], shape=(2, 2), dtype=float32)
The new w1 is:
[[-2.5114694  -1.4596888 ]
 [ 0.47957253  0.8232676 ]]
w2 grad: tf.Tensor(
[[ 0.00255617 -0.14745352  0.14489736]
 [ 0.01113518 -0.64233583  0.6312007 ]], shape=(2, 3), dtype=float32)
The new w2 is:
[[-0.10127809  2.4737267  -2.2724488 ]
 [-1.5055676  -4.878832    3.3843997 ]]
b1 grad: tf.Tensor([-0.5734643  2.01556  ], shape=(2,), dtype=float32)
The new b1 is:
[-1.313268   -0.30777997]
b2 grad: tf.Tensor([ 0.01729538 -0.9976888   0.9803934 ], shape=(3,), dtype=float32)
The new b2 is:
[-0.00864769  0.4988444   0.5098033 ]
